---
# tasks file for alpha

# Standards: 0.11
---

- include: task1.yml
    when: task1

- include: task2.yml
    when: task2

- include: task3.yml
    when: task3

- include: task4.yml
    when: task5

- include: task5.yml
    when: task5