---
# tasks file for alpha

- include: task1.yml
  when: task1

- include: task2.yml
  when: task2

- include: task3.yml
  when: task3

- include: task4.yml
  when: task4

- include: task5.yml
  when: task5

- name: Collect only facts returned by facter
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!any'
      - facter
  debug: 